# Timer before "not in combat anymore"
# DEFAULT 15
timer: 15

# Boost of ores mined
# Easy math: We just multiply how many ores
# we got by the boost's value
# DEFAULT 1
ores-boost: 1

# With iron and gold, you can mine the block, obtain (just believe) 2, place them, break them and obtain 4... etc
# So if it is true, it'll prevent and don't put the ores-boost on iron and gold
# else, it will as they're not really valuable (just for golden apple that can be very bad D; )
# DEFAULT true true
iron-prevent: true
gold-prevent: true


language:
  # Avaible: english, french, custom
  # DEFAULT english
  set: english
  
  # true: When a player dies, it sends a custom message (that doesn't contain the reason why he's dead)
  # if he gets killed, it sends a custom message like "Player was slain by Killer" that can be changed too
  # false: Vanilla death messages
  # DEFAULT true
  custom-death-messages: true
  
  # To find defaults, go on this page https://github.com/GhostCode920/LifeStealSMP/blob/0e8730f93d60df74256ba28fe8321c894be93da6/src/me/ghostcode/lifesteal/language/English.java
  custom:
    nolongerincombat: "&aYou're no longer in combat"
    # $timer$ = timer before no longer in combat
    timer: "&cIn combat for &6$timer$&cs."
    # $player$ = player who got killed
    # $killer$ = player who killed; require custom-death-messages
    playerkilledby: "§6$player$ §ewas slain by §6$killer$ §e!"
    # $player$ = player who died; require custom-death-messages
    playerdeath: "§6$player$ §edied !"
